export const storageKeys = {
  publicLeads: "motomas-public-leads-v1",
  customers: "motomas-customers-v1",
  customerFiles: "motomas-customer-files-v1",
  inventoryUnits: "motomas-inventory-units-v1",
  transferOrders: "motomas-transfer-orders-v1",
  reservations: "motomas-reservations-v1",
  sales: "motomas-sales-v1",
  quotes: "motomas-quotes-v1",
  expedientDocuments: "motomas-expedient-documents-v1",
  creditApplications: "motomas-credit-applications-v1",
  activities: "motomas-activities-v1",
  marketingCampaigns: "motomas-marketing-campaigns-v1",
  accountingJournalEntries: "motomas-accounting-journal-entries-v1",
  accountingVouchers: "motomas-accounting-vouchers-v1",
  accountingDocuments: "motomas-accounting-documents-v1",
  accountingExpenses: "motomas-accounting-expenses-v1",
  accountingPayroll: "motomas-accounting-payroll-v1",
  accountingInventoryCosts: "motomas-accounting-inventory-costs-v1",
  accountingChartAccounts: "motomas-accounting-chart-accounts-v1",
  accountingBanks: "motomas-accounting-banks-v1",
  accountingReconciliations: "motomas-accounting-reconciliations-v1",
  accountingClosures: "motomas-accounting-closures-v1",
  accountingThirdParties: "motomas-accounting-third-parties-v1",
  cashierInvoices: "motomas-cashier-invoices-v1",
  cashierReceipts: "motomas-cashier-receipts-v1",
  cashierNotes: "motomas-cashier-notes-v1",
  cashierClosures: "motomas-cashier-closures-v1",
  demoSession: "motomas-demo-session-v1",
} as const;

export const demoPersistenceKeys = [
  storageKeys.publicLeads,
  storageKeys.customers,
  storageKeys.customerFiles,
  storageKeys.inventoryUnits,
  storageKeys.transferOrders,
  storageKeys.reservations,
  storageKeys.sales,
  storageKeys.quotes,
  storageKeys.expedientDocuments,
  storageKeys.creditApplications,
  storageKeys.activities,
  storageKeys.marketingCampaigns,
  storageKeys.accountingJournalEntries,
  storageKeys.accountingVouchers,
  storageKeys.accountingDocuments,
  storageKeys.accountingExpenses,
  storageKeys.accountingPayroll,
  storageKeys.accountingInventoryCosts,
  storageKeys.accountingChartAccounts,
  storageKeys.accountingBanks,
  storageKeys.accountingReconciliations,
  storageKeys.accountingClosures,
  storageKeys.accountingThirdParties,
  storageKeys.cashierInvoices,
  storageKeys.cashierReceipts,
  storageKeys.cashierNotes,
  storageKeys.cashierClosures,
  storageKeys.demoSession,
] as const;

export type DemoPersistenceKey = (typeof demoPersistenceKeys)[number];
